spring:
  application:
    name: EmployeeModule
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres1
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
